#!/bin/bash

# Programs to start at boot
xrandr -s 3440x1440 -r 120
urxvtd --quiet --opendisplay --fork &
dbus-launch --sh-syntax --exit-with-session; pulseaudio --kill; gentoo-pipewire-launcher &
dunst &
nitrogen --restore &
picom --experimental-backends &
xsetroot -cursor_name left_ptr
sxhkd -c ~/.config/berry/sxhkdrc &

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       30
berryc top_gap            0

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   606060
berryc inner_unfocus_color 484848
berryc text_focus_color    303030
berryc text_unfocus_color  181818

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Fira Sans"
